### ISSUE TITLE
Dependencies cleanup

### ISSUE THREAD

**Issue by robdy** [robdy/robdy.io#406]
# Goal

To review all the dependencies and remove what's not needed

# Approach

Whenever possible, don't use external plugins. If there's an alternative in VS Code or can be easily written, replace it

# Dependencies

- [x]     "@mdx-js/mdx": "^1.6.22", Required by gatsby-plugin-mdx
- [x]     "@mdx-js/react": "^1.6.22", Required by gatsby-plugin-mdx
- [x]     "gatsby": "^3.14.6",
- [ ]     "gatsby-core-utils": "^3.3.0",
- [ ]     "gatsby-plugin-feed": "^3.14.0",
- [ ]     "gatsby-plugin-image": "^1.14.2",
- [x]     "gatsby-plugin-mdx": "^2.14.0", For custom Markdown elements
- [ ]     "gatsby-plugin-react-helmet": "^4.14.0",
- [ ]     "gatsby-plugin-sharp": "^3.14.3",
- [ ]     "gatsby-plugin-sitemap": "^4.10.0",
- [ ]     "gatsby-remark-copy-linked-files": "^4.11.0",
- [ ]     "gatsby-remark-images": "^5.11.0",
- [ ]     "gatsby-remark-prismjs": "^5.11.0",
- [x]     "gatsby-remark-relative-images-v2": "^0.1.5", For images in Netlify CMS
- [ ]     "gatsby-source-filesystem": "^3.14.0",
- [ ]     "gatsby-source-rss-feed": "^1.2.2",
- [ ]     "gatsby-transformer-sharp": "^3.14.0",
- [ ]     "lodash": "^4.17.21",
- [ ]     "lodash-webpack-plugin": "^0.11.6",
- [ ]     "netlify-cms-app": "^2.15.61",
- [ ]     "netlify-cms-media-library-cloudinary": "^1.3.10",
- [ ]     "netlify-cms-media-library-uploadcare": "^0.5.10",
- [ ]     "postcss": "^8.4.5",
- [x]     "prismjs": "^1.25.0", Code highlighting
- [ ]     "prop-types": "^15.6.0",
- [ ]     "react": "^17.0.2",
- [ ]     "react-dom": "^17.0.2",
- [ ]     "react-helmet": "^6.0.0",
- [ ]     "sharp": "^0.31.3", For gatsby-plugin-sharp
- [ ]     "uuid": "^8.3.2",
- [ ]     "webpack": "^5.65.0"

 # devDependencies

- [ ] "prettier": "^2.5.1"

# Not needed
- [x]     "gatsby-remark-table-of-contents": "^1.0.0", #419 
- [x]     "gatsby-plugin-netlify": "^3.14.0", [ref](https://www.gatsbyjs.com/plugins/gatsby-plugin-netlify/)
- [x]     "@react-icons/all-files": "^4.1.0", #706
- [x]     "gatsby-remark-autolink-headers": "^4.11.0", Implemented using MDX in #712
