### ISSUE TITLE
Migrate to gatsby-plugin-mdx v4

### ISSUE THREAD

**Issue by robdy** [robdy/robdy.io#710]
https://www.gatsbyjs.com/plugins/gatsby-plugin-mdx#migrating-from-v3-to-v4

# Tasks

- [x] Updating dependencies - done in https://github.com/robdy/robdy.io/pull/712/commits/5929dfc8eb94be5559570c3aad10fc9328f12809
  - [x] npm remove @mdx-js/mdx
  - [x] npm install gatsby@latest - already in 4.25.1 while [4.0.0 required](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-mdx/CHANGELOG.md#400-2022-08-16)
  - [x] npm install gatsby-plugin-mdx@latest - 4.0.0 required
  - [x] @mdx-js/react@latest - [2.1.2 required](https://www.npmjs.com/package/@mdx-js/react?activeTab=versions)
  - [x] If you used any related plugins like gatsby-remark-images, also update them to their @latest version.
    - [x]  gatsby-remark-relative-images-v2 - 0.15 is the current version
    - [x] gatsby-remark-images - 6.25 is latest-v4
    - [x] gatsby-remark-copy-linked-files - 5.25 is latest-v4
    - [x] gatsby-remark-autolink-headers - 5.25 is latest-v4
    - [x] gatsby-remark-prismjs - 6.25 is latest-v4
- [x] New options in gatsby-config: Move your remarkPlugins and rehypePlugins keys into the new mdxOptions config option - Not applicable
- [x] GFM & ESM-only packages - not applicable
- [x] Updating createPage action in gatsby-node https://github.com/robdy/robdy.io/pull/712/commits/8198b36209e5cae57c59af7573398505c8ca4420
- [x] Updating page templates https://github.com/robdy/robdy.io/pull/712/commits/d6ebb6f07c6ac530686f924679bc77366bcd6dd2
- [x] Updating MDX content https://github.com/robdy/robdy.io/pull/712/commits/cd5b2a7cf917f8a4de01414d26a018f707e782a8
- [ ] Updating MDX nodes
- [ ] v3 to v4: Breaking Changes
  - [ ] Removed plugin options: defaultLayouts, mediaTypes, lessBabel, shouldBlockNodeFromTransformation, commonmark
  - [x] Moved plugin options remarkPlugins and rehypePlugins into mdxOptions - not applicable
  - [x] Removed timeToRead, rawBody, slug, headings, html, mdxAST, wordCount, fileAbsolutePath from the query result. You can check [Extending the GraphQL MDX nodes](https://www.gatsbyjs.com/plugins/gatsby-plugin-mdx#extending-the-graphql-mdx-nodes) to learn how to re-implement some of them on your own. Also check [Updating MDX nodes](https://www.gatsbyjs.com/plugins/gatsby-plugin-mdx#updating-mdx-nodes) for guidance on changing your queries - logged as #714 
  - [ ] gatsby-plugin-mdx only applies to local files (that are sourced with gatsby-source-filesystem)
  - [ ] Removed the ability to use js and json in frontmatter
  - [ ] All [MDX v2 migration](https://mdxjs.com/migrating/v2/) notes apply

# Error

```
failed Building static HTML for pages - 2.677s

 ERROR #95313 

Building static HTML failed for path "/powershell-tip-skip-get/"

See our docs page for more info on this error: https://gatsby.dev/debug-html


  39 |   if (Object.getOwnPropertySymbols) {
  40 |     var symbols = Object.getOwnPropertySymbols(object);
> 41 |     if (enumerableOnly) symbols = symbols.filter(function (sym) {
     | ^
  42 |       return Object.getOwnPropertyDescriptor(object, sym).enumerable;
  43 |     });
  44 |     keys.push.apply(keys, symbols);


  WebpackError: Element type is invalid: expected a string (for built-in components) or a class/function (for composite componen
  ts) but got: undefined.
  
  - esm.js:41 
    [robdy-io]/[@mdx-js]/react/dist/esm.js:41:1
  
  - esm.js:42 
    [robdy-io]/[@mdx-js]/react/dist/esm.js:42:1
  
  - esm.js:45 
    [robdy-io]/[@mdx-js]/react/dist/esm.js:45:1
  
  - esm.js:44 
    [robdy-io]/[@mdx-js]/react/dist/esm.js:44:1
  
  - esm.js:42 
    [robdy-io]/[@mdx-js]/react/dist/esm.js:42:1
  
  - esm.js:45 
    [robdy-io]/[@mdx-js]/react/dist/esm.js:45:1
  
  - esm.js:37 
    [robdy-io]/[@mdx-js]/react/dist/esm.js:37:1
  
  - esm.js:42 
    [robdy-io]/[@mdx-js]/react/dist/esm.js:42:1
  
  - esm.js:45 
    [robdy-io]/[@mdx-js]/react/dist/esm.js:45:1
  
  - esm.js:44 
    [robdy-io]/[@mdx-js]/react/dist/esm.js:44:1
  
  - esm.js:42 
    [robdy-io]/[@mdx-js]/react/dist/esm.js:42:1
  
  - esm.js:45 
    [robdy-io]/[@mdx-js]/react/dist/esm.js:45:1
  
  - esm.js:37 
    [robdy-io]/[@mdx-js]/react/dist/esm.js:37:1
  
  - esm.js:42 
    [robdy-io]/[@mdx-js]/react/dist/esm.js:42:1
  
  - esm.js:36 
    [robdy-io]/[@mdx-js]/react/dist/esm.js:36:1
  
  - esm.js:42 
    [robdy-io]/[@mdx-js]/react/dist/esm.js:42:1
  ```

# Troubleshooting
- [x]  Checked that the same error appears when plugins are removed
- [ ] Check if the same error appears when MDXProvider is removed from Layout.js
Different error:
```
 ERROR #11321  PLUGIN

"gatsby-plugin-feed" threw an error while running the onPostBuild lifecycle:

Cannot query field "html" on type "Mdx".

GraphQL request:9:23
 8 |                     node {
 9 |                       html
   |                       ^
10 |                       fields { slug }



  Error: Cannot query field "html" on type "Mdx".
  GraphQL request:9:23
   8 |                     node {
   9 |                       html
     |                       ^
  10 |                       fields { slug }
```
- [x] Check if the same error appears when components are removed from MDXProvider - yes
- [ ] Check if the same error appears when MDXRenderer is removed from blog-post.js - no
```
 ERROR #11321  PLUGIN

"gatsby-plugin-feed" threw an error while running the onPostBuild lifecycle:

Cannot query field "html" on type "Mdx".

GraphQL request:9:23
 8 |                     node {
 9 |                       html
   |                       ^
10 |                       fields { slug }



  Error: Cannot query field "html" on type "Mdx".
  GraphQL request:9:23
   8 |                     node {
   9 |                       html
     |                       ^
  10 |                       fields { slug }
  
  - internals.js:17 
    [robdy.io]/[gatsby-plugin-feed]/internals.js:17:13
  
  - task_queues:95 processTicksAndRejections
    node:internal/process/task_queues:95:5
  

not finished onPostBuild - 0.157s
```

**Comment by robdy** [comment]
Closed in #712
